lib/promoter.ts
src/app/api/promoter/route.ts

POST na API de PROMOTER criado, agora pode-se inserir um promoter a partir da rota da API

:construction: POST na API de PROMOTER

---

src/app/eventosPromoter/page.tsx
src/app/finalizacaoCompra/page.tsx
src/app/layout.tsx
src/components/FinalizacaoCompra/cardCartao/cardBackGround/index.tsx
src/components/FinalizacaoCompra/cardIngressos/cardBackGround/index.tsx
src/components/FinalizacaoCompra/cardPrecos/cardIngressoPreco/index.tsx

Melhorando a Responsividade da tela de finalização de compra

🐛 Atualizando Responsividade

---

src/app/finalizacaoCompra/page.tsx
src/app/layout.tsx

📱 corrigindo altura da tela em relação a Navbar

---

src/components/EventRegistration/TicketForm/index.tsx

💄 feat: Alteração nas cores do cadastro de ingresso

---

src/app/eventosPromoter/page.tsx
src/app/layout.tsx
src/components/FinalizacaoCompra/cardCartao/cardCartaoItem/index.tsx
src/components/Navbar/Promoter/NavListPromoter/index.tsx
src/components/Navbar/Promoter/ProfileMenuPromoter/index.tsx
src/components/Navbar/SelectContainer/index.tsx

Tela de finalização de compra
Navbar

🚧 Rotas Promoter

---

src/app/admin/eventos/page.tsx

Atualização visual da página de visualizar eventos do adm.

:construction: Atualizando exibição dos eventos adm

---

lib/administrador.ts
lib/cliente.ts
lib/erros.ts
lib/promoter.ts
lib/usuario.ts
src/app/api/administrador/[cpf]/route.ts
src/app/api/cliente/[cpf]/route.ts
src/app/api/login/route.ts
src/app/api/promoter/[cpfORcnpj]/route.ts
src/app/api/usuario/[email]/route.ts
src/app/api/usuario/route.ts

Mais um tipo de erro foi adicionado, agora quando não for possivel fazer o login ou uma API não conseguir puxar o dados de um determinado usuario por não ter conseguido encontrar ele no BD, o ERROR 03 será rotornado pela API

:construction: Novo tipo de ERROR

---

src/app/api/evento/route.ts
src/app/api/usuario/route.ts

API's que já possuem edição de dados ja existentes estão acompanhadas de um comentario contendo as strings usadas para o tipo de alteração, para ver todas as strings disponiveis basta ver o comentario que vem logo acima do metodo PUT

:bulb: docs: Strings de Tipos de Edição

---

src/components/ClientSide/index.tsx
src/components/Navbar/Navbar.tsx
src/components/Navbar/Promoter/ProfileMenuPromoter/index.tsx

Foi consertado o botão de sair do componente
O  botão de meu perfil, vai para a página de perfil do promoter, entretanto fica carregando por muito tempo, e não carrega a página, além disso na tela de loading fica aparecendo a navbar de quando o usuário ainda não está logado

🚧 Modificando ProfileMenu: Navbar Promoter

---

src/components/Navbar/Navbar.tsx
src/components/Navbar/Promoter/ProfileMenuPromoter/index.tsx
src/components/Navbar/SelectContainer/index.tsx

Aparentemente o erro está sendo por causa dos imports

🚧Consertando deploy vercel

---

src/components/FinalizacaoCompra/cardCartao/cardBackGround/index.tsx
src/components/FinalizacaoCompra/cardCartao/cardCartaoItem/index.tsx

Pegando dados do cartão pela API

🚧 Atualizando tela finalização de compra

---

src/app/cliente/finalizacaoCompra/page.tsx
src/components/FinalizacaoCompra/cardIngressos/cardBackGround/index.tsx
src/components/FinalizacaoCompra/cardIngressos/cardIngressosItem/index.tsx

Agora o Card dos ingressos obtém os ingressos do carrinho de compras

🚧 Atualizando tela de finalização de compra

---

src/components/FinalizacaoCompra/cardIngressos/cardBackGround/index.tsx
src/components/FinalizacaoCompra/cardPrecos/CardPreco/index.tsx
src/components/FinalizacaoCompra/cardPrecos/cardIngressoPreco/index.tsx

Agora a tela pega todas as informações do carrinho de compras

🚀 Atualização de tela finalização de Compra

---

src/app/promoter/eventos/page.tsx
src/components/cardEventoPromoter/index.tsx

Agora a página dos eventos deve mostrar os eventos que o promoter possui
!!Necessita de testes junto com o cadastro de eventos

🚧 Atualização EventosPromoter

---

src/app/promoter/eventos/page.tsx

A tela de eventos promoter agora está mostrando os eventos que aquele promoter possui

✨Atualização de tela Eventos Promoter

---

package-lock.json
src/components/FinalizacaoCompra/cardCartao/cardBackGround/index.tsx
src/components/FinalizacaoCompra/cardCartao/dropdownParcelas/index.tsx

Mudando o dropdown  do cartão do cartão para torna-lo mais funcional

🚧 Atualizando tela FinalizaçãoCompra

---

src/components/Admin/Promoters/Cards/Aprovados/index.tsx
src/components/Admin/Promoters/Cards/Pendentes/index.tsx
src/components/Admin/Promoters/Cards/Suspensos/index.tsx

Ajuste na visualização de campos grandes na tela de listagem de promoters.

:lipstick: Inserindo truncamento em grandes textos

---

src/app/promoter/eventos/page.tsx
src/components/cardEventoPromoter/index.tsx

Agora o Card do evento do promoter sinaliza quando ele está suspenso

✨Modificação Card Evento promoter

---

src/components/Admin/NewAdmin/index.tsx

Correção do erro ao enviar os dados via API para cadastrar um novo administrador.

:bug: Fix - Cadastrar novo administrador

---

src/components/Admin/NewAdmin/index.tsx

Correção do chamada do endpoint para cadastrar um novo administrador

:bug: Fiz - Endereço da API cadastro de adm

---

src/app/promoter/eventos/vendas/[id]/page.tsx

Correção do bug que fazia o botão de compartilhar não aparecer em eventos disponíveis.

:bug: Fix: Botão de compartilhar evento promoter

---

src/components/FinalizacaoCompra/cardPrecos/cardIngressoPreco/ButtonFinalizar/index.tsx
src/components/FinalizacaoCompra/cardPrecos/cardIngressoPreco/index.tsx

Agora ao finalizar compra é criada a compra na lista de compras do cliente

✨ Atualização tela de finalização de compra

---

src/components/Admin/Eventos/index.tsx

Correção do bug em que o evento não era excluído por parte do adm.

:bug: Fix: Excluir um evento.
